### ISSUE TITLE
Exam Notifier Not Showing

### ISSUE THREAD

**Issue by Adanze168** [AnKing-VIP/exam-notifier#18]
#### Problem description

I got the exam notifier add-on for Anki (Windows 11) and the latest version. There isn't an option to set an exam date under deck options, nor the notification tab when studying. It's like nothing happened when I installed the add-on. There are the good, easy, hard, and again buttons when I study like the add-on described, but that was always there before I got the add-on.
![image](https://github.com/AnKing-VIP/exam-notifier/assets/147207933/8525c2b1-3a66-4703-bf8d-eafeb09e83c6)

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [x] I've tried to disable other add-ons to see if there are any interactions present
 - [x] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```
    
    Anki 2.1.66 (70506aeb) Python 3.9.15 Qt 6.5.2 PyQt 6.5.2
    Platform: Windows-10-10.0.22621
    Flags: frz=True ao=True sv=3
    Add-ons, last update check: 2023-10-21 10:46:54
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Exam Mode ['2012534915', 2022-07-24T23:03, 'None', '']
    Exam Notifier ['236593452', 2023-01-19T12:12, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    2012534915 236593452
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    
```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```python

```

**Comment by Adanze168** [comment]
@AnKingMed or @glutanimate please help!

**Comment by AnKingMed** [comment]
Can you please delete the addon and try redownloading? https://ankiweb.net/shared/info/236593452

Try it on Anki 2.1.64 or 2.1.65. I did on 2.1.65 Qt6 and it is working

**Comment by bbhavens** [comment]
I can confirm the same issue; shows up just fine on 2.1.64 but upon downloading 2.1.66 is no longer visible in the options screen.  It does, however, seem to be functioning (as I still get the notifications if a card is overdue, I simply can't access the options on the appropriately screen).

**Comment by Adanze168** [comment]
> I can confirm the same issue; shows up just fine on 2.1.64 but upon downloading 2.1.66 is no longer visible in the options screen. It does, however, seem to be functioning (as I still get the notifications if a card is overdue, I simply can't access the options on the appropriately screen).

Actually, I saw this one comment on the website for the addon and it just said to pull down shift when clicking the options under the gear from a deck, and the format will show.

**Comment by AnKingMed** [comment]
good to know! Thank you everyone for sharing. We'll test it on the new 23.10 version and ensure it works
