### ISSUE TITLE
add on does not work in new 24.06.03

### ISSUE THREAD

**Issue by algal06** [AnKing-VIP/exam-notifier#27]
#### Problem description

Hello, 
I first tried it on the 24.04.01 version and i was able to see in the options menu of my deck " add ons" and pick a date but the pop up was not showing up on each card. To troubleshoot this, i tried installing the latest anki version (q5 and q6) and now my add ons are not even showing up under the "options" menu. 

I have successfully downloaded your add on for exam notifier but I am unable to see the pop up menu for enabling the add on in the 24.06.03 version of anki. This is the q5 version of the windows download. I cant see add ons in my menu when I go to options at all. Hoping you can help. 

 -  I've restarted Anki to see if it help
 - I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
- I have no other add ons
 - I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 5.15.2 PyQt 5.15.5
Platform: Windows-10-10.0.19045

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Exam Notifier ['236593452', 2023-01-19T12:12, 'None', '']

===IDs of active AnkiWeb add-ons===
236593452

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

**Comment by AnKingMed** [comment]
@abdnh can you look into this? Maybe related to FSRS?

**Comment by AnKingMed** [comment]
actually going to merge this with the other issue that's active: https://github.com/AnKing-VIP/exam-notifier/issues/26

**Comment by Kadizta98** [comment]
> en realidad voy a fusionar esto con el otro problema que está activo: #26 Solution please... ?
