### ISSUE TITLE
Not notifying exam date if card is still in learning phase

### ISSUE THREAD

**Issue by AnKingMed** [AnKing-VIP/exam-notifier#3]
Reported by a user on patreon who is using long learning intervals and tests/quizzes every week or two

**Comment by ankihelp** [comment]
I am having issues with this as well. The icon is not popping up on my anki cards

**Comment by jaredagordon** [comment]
Any updates on this?

**Comment by AnKingMed** [comment]
We kind of put this on the back burner because it doesn't seem like something super necessary with how Anki is supposed to be used and learning intervals pretty short (i.e. if it's going to be 1-2 days, people generally know they have a test in 1-2 days and rescheduling it isn't going to do much).  @jaredagordon can you give us some info on how you'd use it?

**Comment by jaredagordon** [comment]
Sure:

Currently using it for Step 2. The problem for me isn’t so much the learning phase cards but the relearning phase cards that are mature and have lapsed.

Thanks for responding to this thread after all this time!

**Comment by AnKingMed** [comment]
I'm still not sure I understand how that would be needed. Can you give an example? Like what the intervals would look like in relation to your test, etc?

**Comment by AnKingMed** [comment]
@abdnh would be good to have support for learning cards and re-learning cards too. I've had a few people mention this
